id: I14E13193
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T07:28:49+00:00'
last_modified: '2022-06-08T09:12:14.198731+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24220
  title: དགའ་ལྡན་ཤར་རྩེའི་ཆོས་སྤྱོད་མཛད་རིམ་ངོ་མཚར་བསྟན་པའི་མཛེས་རྒྱན་ཉིན་བྱེད་སྣང་བའི་ཡང་གསལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    C91D:
      image_group_id: I1KG24300
      title: ''
      total_pages: 0
      order: 1
      base_file: C91D.txt
    9F09:
      image_group_id: I1KG24301
      title: ''
      total_pages: 904
      order: 2
      base_file: 9F09.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
